import { createOutlineDraftPage, type OutlineDraftSpec } from '../pages/OutlineDraftPage';
import type { SlideEntry } from '../types/presentation';

function defineDraft(spec: OutlineDraftSpec): SlideEntry {
  return {
    id: `outline-${spec.id.toLowerCase()}`,
    chapter: spec.chapter,
    title: spec.title,
    previewShape: spec.previewShape ?? 'content',
    component: createOutlineDraftPage(spec),
  };
}

export const outlineDraftSlides = {
  courseCover: defineDraft({
    id: 'D01',
    chapter: '課程導覽',
    outlinePath: '一、課程定位／課程主題',
    title: '從介紹產品，到協助客戶做決定',
    purpose: '建立完整課程名稱與顧問式選配的核心定位，讓學員從第一頁就知道這不是產品規格課。',
    onScreenContent: [
      '顧問式助聽器選配實戰',
      '理解、提問、引導，而不是更用力地推銷',
    ],
    interaction: '講師用一句話說明：今天不教更多產品話術，而是重新整理客戶如何做決定。',
    formalDirection: '正式版採偏置大標題封面，保留大量留白，以單一生活對話情境作主視覺。',
    previewShape: 'cover',
  }),
  courseObjectives: defineDraft({
    id: 'D02',
    chapter: '課程導覽',
    outlinePath: '一、課程定位／課程目標',
    title: '今天要帶走的六件事',
    purpose: '把六項學習目標整理成三組能力，讓學員知道課程結束後能實際改變哪些行為。',
    onScreenContent: [
      '認識自己：辨識銷售風格，理解傳統與顧問式銷售的差異',
      '理解客戶：掌握選配流程，用提問找到生活困擾與購買動機',
      '引導決定：回應價格與猶豫，在不施壓下引導下一步',
    ],
    interaction: '三組能力依序揭示；請學員先選出自己最想改善的一組。',
    formalDirection: '正式版以三條能力路徑呈現，每條路徑對應兩項課程目標。',
  }),
  courseAgenda: defineDraft({
    id: 'D03',
    chapter: '課程導覽',
    outlinePath: '二、兩小時課程流程',
    title: '兩小時，我們會走過什麼？',
    purpose: '讓學員預先理解課程節奏、活動形式與休息位置。',
    onScreenContent: [
      '前半場：暖身、銷售風格、顧問式思維、客戶不行動的原因',
      '休息：01:00–01:10',
      '後半場：選配流程、異議實戰、角色扮演、行動承諾',
    ],
    interaction: '先顯示完整時間軸，再標亮目前所在段落；正式版可隨章節更新進度。',
    formalDirection: '使用單一橫向時間軸，不做七張小卡，保留可快速掃讀的節奏。',
  }),
  behaviorContrast: defineDraft({
    id: 'D05',
    chapter: '開場與風格',
    outlinePath: '三、開場與暖身／開場結論',
    title: '客戶排斥的不是購買，是被推銷',
    purpose: '把暖身答案收斂成顧問式銷售的共同語言。',
    onScreenContent: [
      '客戶喜歡：願意聽、理解需求、解釋清楚、提供選擇',
      '客戶不喜歡：急著介紹、先推最高階、製造期限、立刻反駁',
      '顧問式銷售的核心，不是更會說，而是更會理解、提問與引導',
    ],
    interaction: '先由學員說出行為，再揭示歸納；最後只保留核心結論。',
    formalDirection: '正式版用左右對照，但以中間結論作視覺重心，不堆疊十二個小項目。',
    previewShape: 'split',
  }),
  styleOverview: defineDraft({
    id: 'D06',
    chapter: '開場與風格',
    outlinePath: '四、你是哪一種銷售風格？',
    title: '你習慣用哪一種方式幫客戶？',
    purpose: '讓學員辨識自己的自然傾向，並理解每種風格都有優勢與風險。',
    onScreenContent: [
      '產品專家型：專業清楚；盲點是說得多、問得少',
      '關係經營型：容易建立信任；盲點是不敢談價格與決定',
      '問題解決型：分析與建議精準；盲點是忽略情緒',
      '成交導向型：推進有力；盲點是速度超過客戶準備',
    ],
    interaction: '四種風格逐一出現；請學員只選「最像平常的自己」，不能選理想中的自己。',
    formalDirection: '正式版可做四向量定位或水平展開式比較，四種風格保持等重。',
  }),
  styleReflection: defineDraft({
    id: 'D07',
    chapter: '開場與風格',
    outlinePath: '四、你是哪一種銷售風格？／課堂活動',
    title: '找到你的慣性，也找到盲點',
    purpose: '把風格辨識轉成具體經驗，避免停留在性格分類。',
    onScreenContent: [
      '我最接近哪一種風格？',
      '這種風格曾經怎麼幫助我？',
      '我曾經因此錯失什麼成交機會？',
      '沒有最好的風格，只有能不能因客戶而調整',
    ],
    interaction: '兩人一組，每人兩分鐘；最後請一組分享「優勢如何變成盲點」。',
    formalDirection: '正式版用單一反思路徑，讓三個問題像階梯般依序推進。',
  }),
  salesComparison: defineDraft({
    id: 'D08',
    chapter: '顧問式銷售',
    outlinePath: '五、傳統銷售與顧問式銷售',
    title: '同一個產品，兩種完全不同的出發點',
    purpose: '建立傳統銷售與顧問式銷售的清楚判準。',
    onScreenContent: [
      '起點：從產品開始／從客戶生活開始',
      '方法：說服與回答／釐清問題背後的問題',
      '價值：規格越高越好／適合客戶才是最好',
      '目標：完成成交／協助做出合適決定',
    ],
    interaction: '每組對比先只顯示傳統做法，請學員口頭改寫後再揭示顧問式版本。',
    formalDirection: '正式版採一條可滑動的觀點轉換軸，不使用密集比較表。',
    previewShape: 'split',
  }),
  languageWorkshop: defineDraft({
    id: 'D09',
    chapter: '顧問式銷售',
    outlinePath: '五、傳統銷售與顧問式銷售／話術改寫',
    title: '把產品語言，翻成客戶的生活價值',
    purpose: '練習把功能、等級與優惠重新連回客戶的使用情境。',
    onScreenContent: [
      '「這台助聽器有很好的降噪功能。」',
      '「高階款的處理速度比較快。」',
      '「我們這一款目前有優惠。」',
      '改寫原則：先接住客戶說過的場景，再說功能能改善什麼',
    ],
    interaction: '三題分組改寫；每題先保留原句，下一個 fragment 才出現改寫原則。',
    formalDirection: '正式版採水平手風琴，一次展開一題的原句、思考與示範答案。',
  }),
  resistanceReasons: defineDraft({
    id: 'D10',
    chapter: '改變動機',
    outlinePath: '六、客戶為什麼不願意現在處理？',
    title: '客戶為什麼不願意現在處理？',
    purpose: '把十個常見原因整理成可辨識的心理與決策類型。',
    onScreenContent: [
      '病識感：不覺得嚴重、還能忍、困擾的是家人',
      '身份焦慮：怕顯老、怕依賴、抗拒被貼標籤',
      '效果經驗：曾有不好經驗、不確定是否有效',
      '決策風險：家人意見、價位差異、害怕選錯',
    ],
    interaction: '四組原因依序揭示；請學員各舉一個門市中聽過的原句。',
    formalDirection: '正式版以四個心理區域呈現，不做十張同權重小卡。',
  }),
  resistanceCase: defineDraft({
    id: 'D11',
    chapter: '改變動機',
    outlinePath: '六、客戶為什麼不願意現在處理？／案例討論',
    title: '王先生不是不需要，而是還沒準備好',
    purpose: '讓學員從案例資訊中辨識表面拒絕、病識感與身份焦慮。',
    onScreenContent: [
      '68 歲退休教師；雙耳中度聽損；太太反映電視聲過大',
      '本人認為只是偶爾聽不到，平常也沒有太多社交',
      '他說助聽器太貴；女兒想趕快處理，但本人明顯抵抗',
      '討論：真正顧慮、反感句、三個問題、現在該不該介紹產品',
    ],
    interaction: '小組先判斷真正顧慮，再選出最可能讓王先生反感的一句話。',
    formalDirection: '正式版採人物檔案與討論面板的編輯式分割，不使用裝飾性人物卡。',
    previewShape: 'split',
  }),
  resistanceGuidance: defineDraft({
    id: 'D12',
    chapter: '改變動機',
    outlinePath: '六、客戶為什麼不願意現在處理？／講師引導',
    title: '先問，不要急著說服',
    purpose: '示範如何從威嚇式結論轉為協助客戶建立改變理由。',
    onScreenContent: [
      '不要說：「您的聽力已經中度了，不戴只會越來越嚴重。」',
      '問：「您自己在生活中，什麼時候最容易發現聽不清楚？」',
      '問：「太太提醒電視比較大聲時，您自己的感受是什麼？」',
      '問：「如果持續兩三年，您最擔心影響到什麼？」',
    ],
    interaction: '先顯示不建議說法，讓學員說出問題；再逐步揭示三個提問。',
    formalDirection: '正式版以一句被劃掉的結論對照三層追問，視覺重心放在問題深化。',
  }),
  breakPage: defineDraft({
    id: 'D13',
    chapter: '改變動機',
    outlinePath: '兩小時課程流程／01:00–01:10',
    title: '休息十分鐘',
    purpose: '清楚標示上下半場分界，並預告接下來將進入完整選配流程。',
    onScreenContent: [
      '01:10 回到教室',
      '下半場：把理解、檢查、方案與決策串成一條流程',
    ],
    interaction: '停留作為休息背景；不安排 fragment 操作。',
    formalDirection: '正式版可做極簡倒數或靜態章節畫面，避免放置額外教學資訊。',
    previewShape: 'cover',
  }),
  processOverview: defineDraft({
    id: 'D14',
    chapter: '選配流程',
    outlinePath: '七、顧問式選配流程實戰／流程總覽',
    title: '十個步驟，其實只有三個決策階段',
    purpose: '把十個步驟整理成三個心理任務，避免學員只記住作業順序。',
    onScreenContent: [
      '建立信任與理解問題：接待、病史、COSI、聽力檢測',
      '建立介入必要性：報告、介入想法、改變理由',
      '提出方案與協助決策：方案、試聽、最後決定',
    ],
    interaction: '先顯示三階段，再沿著三條路徑補上十個步驟。',
    formalDirection: '正式版使用三段連續路徑，避免十張獨立流程卡造成割裂。',
  }),
  receptionTrust: defineDraft({
    id: 'D15',
    chapter: '選配流程',
    outlinePath: '七、第一階段／1. 接待與第一印象',
    title: '第一印象的目標，是讓客戶敢說真話',
    purpose: '把接待的成功標準從「表現專業」改成「建立安全感」。',
    onScreenContent: [
      '我可以放心說',
      '對方願意聽',
      '對方不會立刻逼我買東西',
      '我的問題會被認真處理',
    ],
    interaction: '四句客戶內心話依序浮現；講師每句各舉一個可觀察的接待行為。',
    formalDirection: '正式版以客戶內在聲音為主角，不用一般服務流程圖。',
  }),
  receptionOpening: defineDraft({
    id: 'D16',
    chapter: '選配流程',
    outlinePath: '七、第一階段／1. 接待與第一印象／開場話術',
    title: '接待時，先說清楚三件事',
    purpose: '建立一段能降低戒心、尊重本人並預告流程的開場。',
    onScreenContent: [
      '確認稱呼，持續把客戶本人放在對話中心',
      '先了解生活與困擾，再檢查與說明方向',
      '今天不一定要做決定，先把問題了解完整',
    ],
    interaction: '講師先示範完整開場，再請學員找出其中降低壓力的三個設計。',
    formalDirection: '正式版呈現一句完整對話，三個關鍵語句用逐步標記取代條列。',
  }),
  lifestyleContext: defineDraft({
    id: 'D17',
    chapter: '選配流程',
    outlinePath: '七、第一階段／2. 病史與生活情境蒐集',
    title: '病史之外，還要看見客戶的生活',
    purpose: '補足既有病史頁較少涵蓋的家庭、工作、社交與使用情境。',
    onScreenContent: [
      '生活角色：和誰住、是否工作、常參與哪些活動',
      '溝通環境：電話、視訊、餐廳、多人談話與最常漏聽的時刻',
      '既有經驗：是否戴過助聽器、對效果與外觀有什麼印象',
      '不要只完成表格，要追問答案背後的場景',
    ],
    interaction: '每組問題揭示後，請學員把一個封閉式問題改成可追問的開放式問題。',
    formalDirection: '正式版用生活軌跡串起家庭、工作與社交，不使用病歷表格視覺。',
  }),
  economicCapacitySignals: defineDraft({
    id: 'D18',
    chapter: '選配流程',
    outlinePath: '七、第一階段／2. 病史與生活情境蒐集',
    title: '客戶的生活裡，藏著經濟能力的線索',
    purpose: '把 D17 看見的生活線索，轉成需要再確認的經濟能力假設。',
    onScreenContent: [
      '家庭照護：是否聘有外籍看護、固定照顧者或長期自費照護安排',
      '過往職涯：退休前職務、專業背景、事業與退休後收入來源',
      '服裝氣質與生活方式：衣著配件、旅遊、社交與消費習慣',
      '家庭支持：兒女職業、陪同情況與誰參與付款決策',
      '自費經驗：過往醫療、保健、3C 與服務支出',
      '原則：線索不是答案，要再用提問確認',
    ],
    interaction: '六組線索逐一揭示，請學員說出下一個不帶預設的確認問題。',
    formalDirection: '正式版採 3×2 共線觀察矩陣，底部強調線索不是結論。',
  }),
  economicAssessmentTiming: defineDraft({
    id: 'D18.5',
    chapter: '選配流程',
    outlinePath: '七、第一階段／2. 病史與生活情境蒐集',
    title: '經濟能力，要在試聽開始前完成判斷',
    purpose: '在安排試聽等級前先確認客戶能承擔的範圍，避免報價後才被動降級或急著說服。',
    onScreenContent: [
      '觀察與判斷區：病史詢問 → COSI → 檢查 → 衛教；前三站持續觀察，衛教後完成等級決策',
      '試聽區：最後決定點（確認試聽等級）→ 試聽',
      '錯誤路徑：先報高價 → 客戶嚇到 → 才降等級或急著說服',
      '理想分岔：成功判斷出預算 → 拿相應款式；還是無頭緒 → i50 出手',
      '前三站持續觀察；衛教後定級，再拿該等級進入試聽',
    ],
    interaction: '五站依序揭示；試聽後先顯示兩個錯誤版本，最後一格以分岔軌道取代兩個錯誤版本。',
    formalDirection: '正式版分成左側四站觀察與判斷區、右側單站試聽區；橘色決定點位於兩區交界。',
  }),
  reportSequence: defineDraft({
    id: 'D19',
    chapter: '選配流程',
    outlinePath: '七、第二階段／5. 講解聽力報告',
    title: '報告不是念數字，而是建立共同理解',
    purpose: '在進入各項結果頁前，先建立統一的報告說明順序。',
    onScreenContent: [
      '先說整體結論，再說主要困難',
      '把結果連回客戶剛才描述的生活情境',
      '確認客戶是否認同，最後才談處理方式',
      '「這和您剛才描述的情況一致嗎？」',
    ],
    interaction: '先讓學員排列五個說明步驟，再揭示建議順序與確認句。',
    formalDirection: '正式版用一條由數據走向生活的閱讀路徑，不做報告清單。',
  }),
  examinationTrustAwarenessIntro: defineDraft({
    id: 'D19.1',
    chapter: '選配流程',
    outlinePath: '七、第二階段／檢查過程中的溝通',
    title: '檢查的過程，也在建立信任與病識感',
    purpose: '提醒聽力師：聽力檢查不只是取得數據，每一次說明、互動與反應，都會影響客戶是否信任專業，也影響他如何理解自己的聽力狀況。',
    onScreenContent: [
      '增加信任感：讓客戶感受到被照顧、被理解，並相信檢查的專業度',
      '增加病識感：讓客戶從檢查反應與生活連結中，看見問題確實存在',
      '檢查結果很重要；客戶如何經歷這段檢查，同樣重要',
    ],
    interaction: '先只出現標題，再揭示「信任感」與「病識感」兩條支線，作為後兩頁的轉場。',
    formalDirection: '正式版採近似章節標題頁的極簡構圖，以「檢查」為起點，分出信任感與病識感兩個方向。',
    previewShape: 'cover',
  }),
  examinationTrustSignals: defineDraft({
    id: 'D19.2',
    chapter: '選配流程',
    outlinePath: '七、第二階段／檢查過程中的溝通／增加信任感',
    title: '如何在檢查過程中增加信任感？',
    purpose: '把照顧感、環境、互動、家屬參與與專業熟練度，轉成客戶在檢查過程中能直接感受到的信任線索。',
    onScreenContent: [
      '關心客人：是否需要先上廁所、時間上是否來得及',
      '提供專業且舒適的檢查環境',
      '保持良好互動：指導語流暢，持續留意客戶反應',
      '讓家人參與檢查過程，並解釋受測者的反應',
      '針對病史安排特別檢查，例如耳鳴',
      '在客人面前完成器具的清潔與消毒',
      '熟悉儀器操作與完整檢查流程',
      '讓客戶知道每一個步驟正在做什麼',
    ],
    interaction: '八項內容先依序揭示；正式實作時再讓學員辨認哪些屬於照顧、互動、環境與專業熟練度。',
    formalDirection: '正式版可將八項線索整理為四組雙項矩陣；目前骨架先完整保留原始內容，不提前壓縮。',
  }),
  examinationAwarenessSignals: defineDraft({
    id: 'D19.3',
    chapter: '選配流程',
    outlinePath: '七、第二階段／檢查過程中的溝通／增加病識感',
    title: '如何在檢查過程中增加病識感？',
    purpose: '讓客戶不只被告知結果，而是透過病史落差、檢查強度、家人參與、氣氛與生活追問，逐步意識到聽力問題與自己的關係。',
    onScreenContent: [
      '結合病史，告知客人 AC 結果與剛才主述不符',
      '告知客人檢查可能比預期多，因為聽損已有一定程度',
      '讓家人陪同參與檢測，實際聆聽刺激音量大小',
      '運用肢體語言：皺眉頭、呈現疑惑感',
      '將輕鬆互動逐步轉為嚴肅的氣氛',
      '再次關心日常生活是否遇到困擾，例如看電視、講電話',
    ],
    interaction: '六項內容逐一揭示；最後回到生活追問，讓學員思考如何由檢查反應接回客戶自己的困擾。',
    formalDirection: '正式版可用「檢查現象 → 專業反應 → 生活確認」三段路徑呈現，避免只做六點條列。',
  }),
  interventionScale: defineDraft({
    id: 'D20',
    chapter: '選配流程',
    outlinePath: '七、第二階段／6. 挖掘客戶對介入的想法',
    title: '介入意願，不是只有願意或不願意',
    purpose: '用量尺找出客戶已經擁有的改變理由，以及還缺少的條件。',
    onScreenContent: [
      '「對助聽器最擔心的是效果、外觀、價格，還是使用麻煩？」',
      '「如果零到十分表示意願，您現在大概是幾分？」',
      '「為什麼不是兩分或三分？」',
      '「要發生什麼，才可能從五分增加到七分？」',
    ],
    interaction: '先請學員猜「五分」後應追問什麼，再揭示向下與向上兩種問法的差異。',
    formalDirection: '正式版用一條可互動量尺，將支持理由與未滿足條件分置兩側。',
  }),
  necessityConversation: defineDraft({
    id: 'D21',
    chapter: '選配流程',
    outlinePath: '七、第二階段／7. 討論介入的必要性',
    title: '讓客戶自己說出改變的理由',
    purpose: '不用恐嚇，而是協助客戶看見現況、損失與想回到的生活。',
    onScreenContent: [
      '現在最困擾的是什麼？它已經影響到什麼？',
      '如果不處理，可能持續失去什麼？',
      '如果改善，希望未來可以做到什麼？',
      '接著才評估：什麼處理方式最能協助達成目標',
    ],
    interaction: '用王先生案例填入四個空格；要求答案必須是客戶的生活語言。',
    formalDirection: '正式版呈現一條由現況走向未來的因果鏈，避免疾病恐嚇視覺。',
  }),
  planSelection: defineDraft({
    id: 'D22',
    chapter: '選配流程',
    outlinePath: '七、第三階段／8. 生活需求、預算與產品等級',
    title: '方案不是等級表，是選擇的理由',
    purpose: '教學員先理解需求與資源配置，再提出少量可比較的方案。',
    onScreenContent: [
      '基本可行方案：先滿足核心需求',
      '建議方案：最符合主要生活情境',
      '完整方案：必要時才提出更完整能力',
      '每個方案都要說清楚適合誰、改善什麼、限制與推薦原因',
    ],
    interaction: '給一個生活案例，請學員刪掉五個產品等級，只留下兩至三個有理由的方案。',
    formalDirection: '正式版用三條不同深度的方案軌道，不使用傳統價格卡或皇冠標記。',
  }),
  demoValidation: defineDraft({
    id: 'D23',
    chapter: '選配流程',
    outlinePath: '七、第三階段／9. 試聽體驗與 DEMO',
    title: '試聽不是表演，而是驗證方案',
    purpose: '讓試聽圍繞客戶在意的情境與可描述的觀察目標。',
    onScreenContent: [
      '試聽前：設定清楚度與環境聲的觀察目標',
      '試聽中：正常對話、安排陪同者、模擬在意情境',
      '試聽後：哪裡最有感、哪裡不習慣、是否接近期待',
      '不要只問：「有沒有比較好？」',
    ],
    interaction: '把常見的「有沒有比較好」改寫成三個能得到具體描述的問題。',
    formalDirection: '正式版採前、中、後三段實驗流程，中央保留客戶主觀回饋。',
  }),
  decisionMethods: defineDraft({
    id: 'D24',
    chapter: '選配流程',
    outlinePath: '七、第三階段／10. 最後決定與促成交',
    title: '成交不是施壓，是幫客戶整理決定',
    purpose: '提供三種自然推進方式，並示範猶豫時如何確認真正卡點。',
    onScreenContent: [
      '總結式：整理目標、試聽感受與目前顧慮',
      '二選一：比較預算控制與情境處理能力',
      '行動式：確認方向後，提出下一個具體安排',
      '仍猶豫時：先問卡點、其他疑慮與需要討論的人',
    ],
    interaction: '同一案例分別用三種方式收尾，讓學員比較哪一種最符合客戶當下狀態。',
    formalDirection: '正式版以三條可選對話路徑呈現，不做銷售漏斗或成交按鈕。',
  }),
  objectionSteps: defineDraft({
    id: 'D25',
    chapter: '異議實戰',
    outlinePath: '八、客戶常見問題與異議處理／五步驟',
    title: '異議不是拒絕，是還有疑慮沒被理解',
    purpose: '建立所有異議都能重複使用的處理順序。',
    onScreenContent: [
      '先聽完，再表示理解',
      '確認真正疑慮，而不是只回答表面問題',
      '只提供與客戶需求有關的資訊',
      '最後確認疑慮是否真的解除',
    ],
    interaction: '五步驟以一句客戶異議走完整流程；每一步先問學員下一步會做什麼。',
    formalDirection: '正式版使用一條往返式對話路徑，強調確認而不是單向說服。',
  }),
  objectionPrice: defineDraft({
    id: 'D26',
    chapter: '異議實戰',
    outlinePath: '八、異議處理／問題二：助聽器太貴了',
    title: '「太貴了」背後，是預算還是效果？',
    purpose: '先辨識客戶擔心付不起，還是不確定改善是否值得。',
    onScreenContent: [
      '「這確實是一筆需要認真評估的支出。」',
      '「主要是總金額超出預期，還是不確定能不能帶來足夠改善？」',
      '效果疑慮：回到需求與試聽',
      '預算問題：再談等級、單雙耳、付款、服務、年限與整體成本',
    ],
    interaction: '讓學員判斷三句「太貴」各自更接近效果疑慮或預算限制。',
    formalDirection: '正式版做成左右展開的雙路徑，而不是價格辯護清單。',
    previewShape: 'split',
  }),
  objectionWaitDependency: defineDraft({
    id: 'D27',
    chapter: '異議實戰',
    outlinePath: '八、異議處理／問題三與問題四',
    title: '「還不嚴重」與「會不會依賴」',
    purpose: '處理病識感不足與錯誤風險認知，同時保留客戶決定權。',
    onScreenContent: [
      '還不嚴重：先區分哪些情況可接受、哪些已造成困擾',
      '共同約定觀察期限，以及哪些變化出現時要重新評估',
      '依賴疑慮：習慣清楚溝通，不等於助聽器讓聽力變差',
      '透過逐步適應與後續調整，避免一開始聲音太刺激',
    ],
    interaction: '兩組異議分別由學員找出「先理解」與「提供資訊」應該說什麼。',
    formalDirection: '正式版採兩段對話對照，避免用醫療警告圖示製造焦慮。',
    previewShape: 'split',
  }),
  objectionFamilyConsider: defineDraft({
    id: 'D28',
    chapter: '異議實戰',
    outlinePath: '八、異議處理／問題五與問題六',
    title: '「回去討論」與「再考慮看看」',
    purpose: '尊重延後決定，同時確認討論對象、真正卡點與下一步。',
    onScreenContent: [
      '回去討論：會和誰談？對方最關心效果、價格還是適應？',
      '主動整理檢查結果、建議方案與差異，降低轉述負擔',
      '再考慮：目前最需要考慮的是哪一個部分？',
      '若仍不願說明，尊重決定並約定後續確認方式',
    ],
    interaction: '辨識「尊重客戶」與「被動結束對話」的差別，練習提出不施壓的下一步。',
    formalDirection: '正式版以兩條未完成的對話線收束到相同的後續節點。',
    previewShape: 'split',
  }),
  roleplayBrief: defineDraft({
    id: 'D29',
    chapter: '異議實戰',
    outlinePath: '九、角色扮演活動／客戶角色卡與聽力師任務',
    title: '三分鐘顧問式對話',
    purpose: '讓學員在限制時間內，把探索情境、確認顧慮與下一步串起來。',
    onScreenContent: [
      '客戶：65 歲，每週與朋友聚餐；覺得太貴，也怕看起來老',
      '客戶不直接拒絕，只會一直說：「我再考慮看看。」',
      '聽力師：找出生活情境與真正顧慮，提出一個合適下一步',
      '限制：不急著介紹產品，至少使用三個開放式問題',
    ],
    interaction: '兩人一組輪流扮演；每輪三分鐘，結束後保留一分鐘回饋。',
    formalDirection: '正式版用清楚的角色分界與倒數計時，不加入裝飾性人物插畫。',
    previewShape: 'split',
  }),
  roleplayObserver: defineDraft({
    id: 'D30',
    chapter: '異議實戰',
    outlinePath: '九、角色扮演活動／觀察者檢核',
    title: '觀察的不是話術，是客戶有沒有被理解',
    purpose: '讓回饋聚焦可觀察行為，而不是個人風格好不好。',
    onScreenContent: [
      '傾聽：聽力師是否說得比客戶多？是否先理解再回答？',
      '探索：是否追問具體情境？是否找到真正顧慮？',
      '時機：是否過早介紹產品？',
      '推進：是否協助客戶做出下一步？客戶是否感到被理解？',
    ],
    interaction: '觀察者只回饋一個做得好的行為，以及一個下一輪要調整的行為。',
    formalDirection: '正式版做成可點選的檢核軌跡，結果只顯示行為，不評分人格。',
  }),
  summaryUnderstand: defineDraft({
    id: 'D31',
    chapter: '課程總結',
    outlinePath: '十、課程總結／顧問式銷售五個核心',
    title: '先理解人，再提出方案',
    purpose: '收斂顧問式銷售前半段的三個核心順序。',
    onScreenContent: [
      '先理解人，再理解問題',
      '先談生活，再談產品',
      '先建立改變理由，再提出方案',
    ],
    interaction: '三句依序出現，請學員各用一個今天的案例補充。',
    formalDirection: '正式版以三句大字佔滿畫面，避免重新解釋全部課程內容。',
    previewShape: 'cover',
  }),
  summaryDecision: defineDraft({
    id: 'D32',
    chapter: '課程總結',
    outlinePath: '十、課程總結／顧問式銷售五個核心',
    title: '成交，是協助客戶做出合適決定',
    purpose: '用最後兩個核心重新定義價格與成交。',
    onScreenContent: [
      '價格要和價值一起討論',
      '成交不是說服，而是協助客戶做決定',
    ],
    interaction: '請學員說出傳統成交與顧問式成交最大的行為差異。',
    formalDirection: '正式版使用高對比雙句收尾，讓「價值」與「決定」成為視覺焦點。',
    previewShape: 'cover',
  }),
  actionCommitment: defineDraft({
    id: 'D33',
    chapter: '課程總結',
    outlinePath: '十、課程總結／最後行動題與結尾',
    title: '下一次選配，我準備改變什麼？',
    purpose: '把課程內容轉成下一次工作現場可執行的行動承諾。',
    onScreenContent: [
      '我準備少說哪一句話？',
      '我準備多問客戶哪一個問題？',
      '好的選配，是讓客戶在充分理解後，為自己的生活做出選擇',
    ],
    interaction: '安靜書寫一分鐘；每位學員帶走一個少說與一個多問。',
    formalDirection: '正式版保留大量書寫停頓與單一結尾句，不再增加新觀念。',
    previewShape: 'cover',
  }),
} as const;
